name: Asset update
on:
  push:
    branches:
    - main
jobs:
  master:
    name: Push to masmainter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: WordPress.org asset update
      uses: 10up/action-wordpress-plugin-asset-update@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }} 